name: Semgrep

on:
  push:
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep

    steps:
      - uses: actions/checkout@v4

      - run: semgrep scan --config auto